# Generated by Django 2.1.7 on 2019-03-11 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Enter last name', max_length=200, verbose_name='Last name')),
                ('email_address', models.EmailField(help_text='Enter email address.', max_length=254)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='Enter last name', max_length=200, verbose_name='School name')),
                ('school_ID_Number', models.IntegerField(help_text='Enter the school registration ID', verbose_name='School ID number')),
                ('number_of_teachers', models.IntegerField(help_text='Enter the number of teaching stuff', verbose_name='Number of Teachers in School')),
                ('number_of_students', models.IntegerField(help_text='Enter the total number of students', verbose_name='Total students')),
                ('school_location', models.CharField(help_text='Enter "County/Constituence/Town"', max_length=200, verbose_name='School Location')),
                ('year_established', models.DateField(help_text='Enter the date in which school was established', verbose_name='Date Established')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Enter last name', max_length=200, verbose_name='Last name')),
                ('admission_number', models.IntegerField(help_text='Enter admission number', unique=True, verbose_name='Admission number')),
                ('Date_of_Birth', models.DateField(help_text='Enter date of birth', verbose_name='Date of birth')),
                ('current_class', models.IntegerField(help_text="Enter the student's current class", verbose_name='current class')),
                ('home_town', models.CharField(help_text='Enter the location "County/Constituence/Town"', max_length=200, verbose_name='Home town')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.School')),
            ],
            options={
                'ordering': ['admission_number'],
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(help_text='students names', to='application.Student'),
        ),
    ]
