# Generated by Django 2.1.7 on 2019-03-11 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AddField(
            model_name='school',
            name='school_category',
            field=models.CharField(choices=[('PRI_SCH', 'Primary School'), ('SEC_SCH', 'Secondary School')], default='SEC_SCH', help_text='Select school level', max_length=20, verbose_name='School level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_students',
            field=models.IntegerField(default=200, help_text='Enter the total number of students', verbose_name='Total students'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_teachers',
            field=models.IntegerField(default=40, help_text='Enter the number of teaching stuff', verbose_name='Number of Teachers in School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_ID_Number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='School ID Number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_location',
            field=models.CharField(blank=True, help_text='Enter "County/Constituence/Town"', max_length=200, verbose_name='School Location'),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_established',
            field=models.DateField(default='01/01/2000', help_text='Enter the date in which school was established', verbose_name='Date Established'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.PositiveSmallIntegerField(help_text='Enter admission number', unique=True, verbose_name='Admission number'),
        ),
    ]
