# Generated by Django 2.1.7 on 2019-03-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190311_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='home_town',
            field=models.CharField(blank=True, help_text='Enter the location "County/Constituence/Town"', max_length=200, verbose_name='Home town'),
        ),
    ]
