# Generated by Django 2.1.7 on 2019-03-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190312_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date_of_Birth',
            field=models.DateField(default='1998-02-02', help_text='Enter date of birth', verbose_name='Date of birth'),
        ),
    ]
