# Generated by Django 2.1.7 on 2019-03-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190312_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_id', 'school_category', 'number_of_students', 'number_of_teachers']},
        ),
        migrations.RemoveField(
            model_name='parent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_ID_Number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_id',
            field=models.AutoField(db_column='parent_id', default=50, help_text='This the parent unique id', primary_key=True, serialize=False, verbose_name='Parent ID'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.AutoField(db_column='school_ID', default=341, help_text='Enter the school ID', primary_key=True, serialize=False, verbose_name='School ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.AutoField(db_column='student_id', default=924, help_text='This is the unique student ID', primary_key=True, serialize=False, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email_address',
            field=models.EmailField(db_column='email_address', help_text='Enter email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(db_column='first_name', help_text='Enter first name', max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(db_column='last_name', help_text='Enter last name', max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(db_column='student', help_text='students names', to='application.Student'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_students',
            field=models.IntegerField(db_column='number_of_students', default=200, help_text='Enter the total number of students', verbose_name='Total students'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_teachers',
            field=models.IntegerField(db_column='number_of_teachers', default=40, help_text='Enter the number of teaching stuff', verbose_name='Number of Teachers in School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_category',
            field=models.CharField(choices=[('PRI_SCH', 'Primary School'), ('SEC_SCH', 'Secondary School')], db_column='school_category', default='SEC_SCH', help_text='Select school level', max_length=20, verbose_name='School level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_location',
            field=models.CharField(blank=True, db_column='school_location', help_text='Enter "County/Constituence/Town"', max_length=200, verbose_name='School Location'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(db_column='school_name', help_text='Enter last name', max_length=200, verbose_name='School name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_established',
            field=models.DateField(db_column='year_established', default='01/01/2000', help_text='Enter the date in which school was established', verbose_name='Date Established'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Date_of_Birth',
            field=models.DateField(db_column='date_of_birth', default='1998-02-02', help_text='Enter date of birth', verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.PositiveSmallIntegerField(db_column='admission_number', help_text='Enter admission number', unique=True, verbose_name='Admission number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.IntegerField(db_column='current_class', help_text="Enter the student's current class", verbose_name='current class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='first_name', help_text='Enter first name', max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_town',
            field=models.CharField(blank=True, db_column='home_town', help_text='Enter the location "County/Constituence/Town"', max_length=200, verbose_name='Home town'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='last_name', help_text='Enter last name', max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(db_column='school', on_delete=django.db.models.deletion.CASCADE, to='application.School'),
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parents',
        ),
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
