# Generated by Django 2.1.7 on 2019-03-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190313_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.AutoField(db_column='school_ID', default=774, help_text='Enter the school ID', primary_key=True, serialize=False, verbose_name='School ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(db_column='student_id', default=254, help_text='This is the unique student ID', primary_key=True, serialize=False, verbose_name='Student ID'),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
