# Generated by Django 2.1.7 on 2019-03-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190313_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.AutoField(db_column='parent_id', help_text='This the parent unique id', primary_key=True, serialize=False, verbose_name='Parent ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.AutoField(db_column='school_ID', help_text='Enter the school ID', primary_key=True, serialize=False, verbose_name='School ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(db_column='student_id', help_text='This is the unique student ID', primary_key=True, serialize=False, verbose_name='Student ID'),
        ),
    ]
