# Generated by Django 2.1.7 on 2019-03-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_category', 'number_of_students', 'number_of_teachers']},
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_id',
        ),
        migrations.AddField(
            model_name='school',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
