# Generated by Django 2.1.7 on 2019-03-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20190313_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.AutoField(db_column='school_ID', default=1, help_text='Enter the school ID', primary_key=True, serialize=False, verbose_name='School ID'),
            preserve_default=False,
        ),
    ]
