# Generated by Django 2.1.7 on 2019-03-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20190313_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, default=56, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
