# Generated by Django 2.1.7 on 2019-03-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
