# Generated by Django 2.1.7 on 2019-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='parent',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_ID_Number',
            field=models.PositiveSmallIntegerField(db_column='school_ID', default=12, help_text='Enter Registration number of school', unique=True, verbose_name='Admission number'),
            preserve_default=False,
        ),
    ]
